--------------------------------------------------------
--  Fichier créé - lundi-mai-22-2023
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BOOKING
--------------------------------------------------------

CREATE TABLE "BOOKING"
(	"ID" NUMBER(*,0),
     "LISTING_ID" NUMBER(*,0),
     "GUEST_ID" NUMBER(*,0),
     "ARRIVAL" DATE,
     "NIGHTS" NUMBER(*,0)
) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CITY
--------------------------------------------------------

CREATE TABLE "CITY"
(	"ID" NUMBER(*,0),
     "NAME" VARCHAR2(255 BYTE)
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table GUEST
--------------------------------------------------------

CREATE TABLE "GUEST"
(	"ID" NUMBER(*,0),
     "NAME" VARCHAR2(255 BYTE),
     "EMAIL" VARCHAR2(255 BYTE)
) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HOST
--------------------------------------------------------

CREATE TABLE "HOST"
(	"ID" NUMBER(*,0),
     "NAME" VARCHAR2(255 BYTE),
     "HOST_SINCE" DATE DEFAULT NULL,
     "HOST_RESPONSE_TIME" VARCHAR2(255 BYTE) DEFAULT NULL,
     "HOST_ACCEPTANCE_RATE" NUMBER(5,2) DEFAULT NULL,
     "HOST_IS_SUPERHOST" NUMBER(*,0) DEFAULT NULL
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LISTING
--------------------------------------------------------

CREATE TABLE "LISTING"
(	"ID" NUMBER(*,0),
     "URL" VARCHAR2(255 BYTE) DEFAULT NULL,
     "NAME" VARCHAR2(255 BYTE),
     "DESCRIPTION" VARCHAR2(255 BYTE) DEFAULT NULL,
     "PICTURE_URL" VARCHAR2(255 BYTE) DEFAULT NULL,
     "LATITUDE" VARCHAR2(255 BYTE) DEFAULT NULL,
     "LONGITUDE" VARCHAR2(255 BYTE) DEFAULT NULL,
     "PRICE" NUMBER(10,2) DEFAULT NULL,
     "MINIMUM_NIGHTS" NUMBER(*,0) DEFAULT NULL,
     "MAXIMUM_NIGHTS" NUMBER(*,0) DEFAULT NULL,
     "AVAILABILITY_365" NUMBER(5,2) DEFAULT NULL,
     "NUMBER_OF_REVIEWS" NUMBER(*,0) DEFAULT NULL,
     "REVIEW_SCORES_RATING" NUMBER(5,2) DEFAULT NULL,
     "INSTANT_BOOKABLE" NUMBER(*,0) DEFAULT NULL,
     "HOST_ID" NUMBER(*,0) DEFAULT NULL,
     "CITY_ID" NUMBER(*,0) DEFAULT NULL,
     "PROPERTY_TYPE_ID" NUMBER(*,0) DEFAULT NULL
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROPERTY_TYPE
--------------------------------------------------------

CREATE TABLE "PROPERTY_TYPE"
(	"ID" NUMBER(*,0),
     "NAME" VARCHAR2(255 BYTE) DEFAULT NULL
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CITY
--------------------------------------------------------

ALTER TABLE "CITY" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "CITY" ADD PRIMARY KEY ("ID")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LISTING
--------------------------------------------------------

ALTER TABLE "LISTING" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "LISTING" ADD PRIMARY KEY ("ID")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BOOKING
--------------------------------------------------------

ALTER TABLE "BOOKING" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "BOOKING" ADD PRIMARY KEY ("ID")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROPERTY_TYPE
--------------------------------------------------------

ALTER TABLE "PROPERTY_TYPE" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "PROPERTY_TYPE" ADD PRIMARY KEY ("ID")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GUEST
--------------------------------------------------------

ALTER TABLE "GUEST" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "GUEST" ADD PRIMARY KEY ("ID")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table HOST
--------------------------------------------------------

ALTER TABLE "HOST" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "HOST" ADD PRIMARY KEY ("ID")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOOKING
--------------------------------------------------------

ALTER TABLE "BOOKING" ADD CONSTRAINT "FKBOOKINGLISTING" FOREIGN KEY ("LISTING_ID")
    REFERENCES "LISTING" ("ID") ENABLE;
ALTER TABLE "BOOKING" ADD CONSTRAINT "FKGUESTBOOKING" FOREIGN KEY ("GUEST_ID")
    REFERENCES "GUEST" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LISTING
--------------------------------------------------------

ALTER TABLE "LISTING" ADD CONSTRAINT "FKLISTINGCITY" FOREIGN KEY ("CITY_ID")
    REFERENCES "CITY" ("ID") ENABLE;
ALTER TABLE "LISTING" ADD CONSTRAINT "FKLISTINGHOST" FOREIGN KEY ("HOST_ID")
    REFERENCES "HOST" ("ID") ENABLE;
ALTER TABLE "LISTING" ADD CONSTRAINT "FKLISTINGPROPERTYTYPE" FOREIGN KEY ("PROPERTY_TYPE_ID")
    REFERENCES "PROPERTY_TYPE" ("ID") ENABLE;--------------------------------------------------------
--  Fichier créé - lundi-mai-22-2023
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BOOKING
--------------------------------------------------------

CREATE TABLE "BOOKING"
(	"ID" NUMBER(*,0),
     "LISTING_ID" NUMBER(*,0),
     "GUEST_ID" NUMBER(*,0),
     "ARRIVAL" DATE,
     "NIGHTS" NUMBER(*,0)
) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CITY
--------------------------------------------------------

CREATE TABLE "CITY"
(	"ID" NUMBER(*,0),
     "NAME" VARCHAR2(255 BYTE)
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table GUEST
--------------------------------------------------------

CREATE TABLE "GUEST"
(	"ID" NUMBER(*,0),
     "NAME" VARCHAR2(255 BYTE),
     "EMAIL" VARCHAR2(255 BYTE)
) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HOST
--------------------------------------------------------

CREATE TABLE "HOST"
(	"ID" NUMBER(*,0),
     "NAME" VARCHAR2(255 BYTE),
     "HOST_SINCE" DATE DEFAULT NULL,
     "HOST_RESPONSE_TIME" VARCHAR2(255 BYTE) DEFAULT NULL,
     "HOST_ACCEPTANCE_RATE" NUMBER(5,2) DEFAULT NULL,
     "HOST_IS_SUPERHOST" NUMBER(*,0) DEFAULT NULL
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LISTING
--------------------------------------------------------

CREATE TABLE "LISTING"
(	"ID" NUMBER(*,0),
     "URL" VARCHAR2(255 BYTE) DEFAULT NULL,
     "NAME" VARCHAR2(255 BYTE),
     "DESCRIPTION" VARCHAR2(255 BYTE) DEFAULT NULL,
     "PICTURE_URL" VARCHAR2(255 BYTE) DEFAULT NULL,
     "LATITUDE" VARCHAR2(255 BYTE) DEFAULT NULL,
     "LONGITUDE" VARCHAR2(255 BYTE) DEFAULT NULL,
     "PRICE" NUMBER(10,2) DEFAULT NULL,
     "MINIMUM_NIGHTS" NUMBER(*,0) DEFAULT NULL,
     "MAXIMUM_NIGHTS" NUMBER(*,0) DEFAULT NULL,
     "AVAILABILITY_365" NUMBER(5,2) DEFAULT NULL,
     "NUMBER_OF_REVIEWS" NUMBER(*,0) DEFAULT NULL,
     "REVIEW_SCORES_RATING" NUMBER(5,2) DEFAULT NULL,
     "INSTANT_BOOKABLE" NUMBER(*,0) DEFAULT NULL,
     "HOST_ID" NUMBER(*,0) DEFAULT NULL,
     "CITY_ID" NUMBER(*,0) DEFAULT NULL,
     "PROPERTY_TYPE_ID" NUMBER(*,0) DEFAULT NULL
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROPERTY_TYPE
--------------------------------------------------------

CREATE TABLE "PROPERTY_TYPE"
(	"ID" NUMBER(*,0),
     "NAME" VARCHAR2(255 BYTE) DEFAULT NULL
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CITY
--------------------------------------------------------

ALTER TABLE "CITY" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "CITY" ADD PRIMARY KEY ("ID")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LISTING
--------------------------------------------------------

ALTER TABLE "LISTING" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "LISTING" ADD PRIMARY KEY ("ID")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BOOKING
--------------------------------------------------------

ALTER TABLE "BOOKING" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "BOOKING" ADD PRIMARY KEY ("ID")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROPERTY_TYPE
--------------------------------------------------------

ALTER TABLE "PROPERTY_TYPE" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "PROPERTY_TYPE" ADD PRIMARY KEY ("ID")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GUEST
--------------------------------------------------------

ALTER TABLE "GUEST" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "GUEST" ADD PRIMARY KEY ("ID")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table HOST
--------------------------------------------------------

ALTER TABLE "HOST" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "HOST" ADD PRIMARY KEY ("ID")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOOKING
--------------------------------------------------------

ALTER TABLE "BOOKING" ADD CONSTRAINT "FKBOOKINGLISTING" FOREIGN KEY ("LISTING_ID")
    REFERENCES "LISTING" ("ID") ENABLE;
ALTER TABLE "BOOKING" ADD CONSTRAINT "FKGUESTBOOKING" FOREIGN KEY ("GUEST_ID")
    REFERENCES "GUEST" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LISTING
--------------------------------------------------------

ALTER TABLE "LISTING" ADD CONSTRAINT "FKLISTINGCITY" FOREIGN KEY ("CITY_ID")
    REFERENCES "CITY" ("ID") ENABLE;
ALTER TABLE "LISTING" ADD CONSTRAINT "FKLISTINGHOST" FOREIGN KEY ("HOST_ID")
    REFERENCES "HOST" ("ID") ENABLE;
ALTER TABLE "LISTING" ADD CONSTRAINT "FKLISTINGPROPERTYTYPE" FOREIGN KEY ("PROPERTY_TYPE_ID")
    REFERENCES "PROPERTY_TYPE" ("ID") ENABLE;